# Generated by Django 4.2 on 2025-12-23 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da atividade')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ordens_servico/')),
                ('status', models.CharField(choices=[('aberto', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída')], default='aberto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_servico.checklistitem')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='os_servico.ordemservico')),
            ],
            options={
                'unique_together': {('ordem_servico', 'checklist_item')},
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='checklist',
            field=models.ManyToManyField(related_name='ordens_servico', through='os_servico.OrdemServicoChecklist', to='os_servico.checklistitem'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to=settings.AUTH_USER_MODEL),
        ),
    ]
