# Generated by Django 4.2 on 2025-12-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.TextField(default=1, verbose_name='Nome do cliente'),
            preserve_default=False,
        ),
    ]
