# Generated by Django 4.2 on 2025-12-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_servico', '0002_ordemservico_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome do cliente'),
        ),
    ]
