# Generated by Django 4.2 on 2025-12-25 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('os_servico', '0003_alter_ordemservico_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to=settings.AUTH_USER_MODEL),
        ),
    ]
