# Generated by Django 4.2 on 2025-12-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico')], default='tecnico', max_length=10),
        ),
    ]
